# Generated by Django 4.0.3 on 2022-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_brands_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('rentalprice', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_img')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
