# Generated by Django 4.0.3 on 2022-03-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_category_product_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
