# Generated by Django 4.0.3 on 2022-03-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
