# Generated by Django 4.0.3 on 2022-04-06 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('nickname', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10)),
                ('second_number', models.CharField(max_length=10)),
                ('disctrict', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('local_area', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=150)),
                ('birthday', models.DateField(help_text='User birthdate')),
                ('gender', models.CharField(max_length=150)),
                ('profile_picture', models.ImageField(upload_to='static/profileImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
