# Generated by Django 4.0.3 on 2022-05-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/order/image')),
                ('product', models.CharField(default='', max_length=1000)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(max_length=10)),
                ('total', models.CharField(default='', max_length=1000)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=18)),
                ('start_date', models.DateField(help_text='Start rental date')),
                ('end_date', models.DateField(help_text='End rental date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Deliver', 'Deliver'), ('Compleate', 'Sucess')], max_length=10)),
                ('note', models.CharField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
