# Generated by Django 4.0.3 on 2022-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_order_note_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Deliver', 'Deliver'), ('Sucess', 'Sucess')], max_length=10),
        ),
    ]
